services:
  momiwillbepilot-frontend:
    build:
      context: ./
      dockerfile: dockerfile
    networks:
      - app-momiwillbepilot
  momiwillbepilot-cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - app-momiwillbepilot


networks:
  app-momiwillbepilot:
    driver: bridge